name: dsp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  # - streamlit
  # - plotly
  # - pandas
  # - numpy
  # - openai
  # - python-dotenv
  # - requests
  # - yt-dlp
  # - langchain
  # - faiss-cpu
  # - langchain-openai
  # - tiktoken
  # - fpdf
  # - markdown
  # - python-docx
  # - langchain-community
  # - rich
  # - pydantic<2.0
  # - chromadb
  # - isodate
  # - pydub
  # - pytube 
  # - youtube-search-python
  # - scikit-learn
  # - matplotlib      
  # - Pillow
  # - transformers
  # - sentence-transformers
  # - requests
  # - BeautifulSoup4